### ISSUE TITLE
car drop-off colors

### ISSUE THREAD

**Issue by JCoder121** [JCoder121/carsim#5]
car doesn't change color on the drop-off. something to do with being in the while loop, for ball in list does the calculations and THEN it updates with colors, but I want to update colors when it has stopped and is dropping people off. want to see if I can merge one ball in list equation to both calculate and change/update colors

**Comment by AnirudhChaudhary** [comment]
You could overlap the rectangle color with another rectangle of a different color

**Comment by JCoder121** [comment]
cars now drop off and change colors. Red if have not dropped off and turns yellow if has dropped off
