### ISSUE TITLE
car drop-off locations

### ISSUE THREAD

**Issue by JCoder121** [JCoder121/carsim#6]
car can't decide where to stop for drop-off. solve this second, because the changing color will indicate exactly which cars don't stop. could be because the coordinates are off for the road frame when assigning to car.

**Comment by AnirudhChaudhary** [comment]
We can assign certain zones to where the cars will drop off

**Comment by AnirudhChaudhary** [comment]
A random number generator will create a number that corresponds to a zone in which it will stop at

**Comment by JCoder121** [comment]
cars all stop now correctly
